services:
  web:
    build: 
      context: .
      target: deps # TUYỆT CHIÊU: Chỉ lấy stage đầu tiên của Dockerfile để có sẵn OpenSSL, không build toàn bộ app
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://admin:secretpassword@db:5432/khongmatuy_db
    
    volumes:
      - .:/app
      # Đặt tên cho volume để Docker quản lý cache tốt hơn, tránh lỗi mất thư viện
      - node_modules_vol:/app/node_modules
      - next_vol:/app/.next
    
    # ĐÂY LÀ CHÌA KHÓA: Chuỗi lệnh tự động hóa hoàn toàn khi boot
    command: npm run docker:dev
             
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: khongmatuy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules_vol: # Thêm dòng này
  next_vol:         # Thêm dòng này