services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Giữ nguyên link DB của bạn
      - DATABASE_URL=postgresql://admin:secretpassword@db:5432/khongmatuy_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: khongmatuy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: